/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Logica.Circulo;
import Logica.Cuadrado;
import Logica.FiguraGeometrica;
import Logica.Rectangulo;

/**
 *
 * @author estudiantes
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    
    
    
     double[] operaciones = new double[2];
    
   
     void liskov(FiguraGeometrica fg){       
        
        // operaciones[0] almacena el valor del area
        fg.calcularArea();
        operaciones[0] = fg.getArea();
        
        
        // operaciones[1] almacena el valor del perimetro
        fg.calcularPerimetro();
        operaciones[1] = fg.getPerimetro();
    }
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnrectangulo = new javax.swing.JButton();
        txtbase = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtaltura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtareaR = new javax.swing.JLabel();
        txtperimetroR = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtradio = new javax.swing.JTextField();
        btncirculo = new javax.swing.JButton();
        txtareaC = new javax.swing.JLabel();
        txtperimetroC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btncuadrado = new javax.swing.JButton();
        txtlado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtareaCu = new javax.swing.JLabel();
        txtperimetroCu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnrectangulo.setText("Calcular");
        btnrectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrectanguloActionPerformed(evt);
            }
        });
        jPanel3.add(btnrectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 104, 90, 38));
        jPanel3.add(txtbase, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 35, 154, -1));

        jLabel4.setText("Ingrese la base: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 38, -1, -1));
        jPanel3.add(txtaltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 66, 154, -1));

        jLabel5.setText("Ingrese la altura: ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 69, -1, -1));
        jPanel3.add(txtareaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 195, -1, -1));
        jPanel3.add(txtperimetroR, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 213, -1, -1));

        jTabbedPane1.addTab("Rectangulo", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Ingrese el radio: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 38, -1, -1));
        jPanel1.add(txtradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 35, 173, -1));

        btncirculo.setText("Calcular");
        btncirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncirculoActionPerformed(evt);
            }
        });
        jPanel1.add(btncirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 73, 90, 39));
        jPanel1.add(txtareaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 146, -1, -1));
        jPanel1.add(txtperimetroC, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 164, -1, -1));

        jTabbedPane1.addTab("Circulo", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncuadrado.setText("Calcular");
        btncuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuadradoActionPerformed(evt);
            }
        });
        jPanel2.add(btncuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 73, 90, 31));
        jPanel2.add(txtlado, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 35, 112, -1));

        jLabel3.setText("Ingrese la longitud del lado: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 38, -1, -1));
        jPanel2.add(txtareaCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 161, -1, -1));
        jPanel2.add(txtperimetroCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 193, -1, -1));

        jTabbedPane1.addTab("Cuadrado", jPanel2);

        jLabel1.setText("Calculador de Areas y perimetros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncirculoActionPerformed
        // TODO add your handling code here:
        
        double radio;
                radio = Double.parseDouble(txtradio.getText());
                
                Circulo miCirculo = new Circulo(radio);               
                liskov(miCirculo);
                
                txtperimetroC.setText("El perimetro es: "+Math.rint(operaciones[1]*100)/100);
                txtareaC.setText("El area es: "+Math.rint(operaciones[0]*100)/100);
        
    }//GEN-LAST:event_btncirculoActionPerformed

    private void btncuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuadradoActionPerformed
        // TODO add your handling code here:
        
        double lado;
                
                lado = Double.parseDouble(txtlado.getText());
                
                Cuadrado miCuadrado = new Cuadrado(lado);
                liskov(miCuadrado);
                
                txtperimetroCu.setText("El perimetro es: "+Math.rint(operaciones[1]*100)/100);
                txtareaCu.setText("El area es: "+Math.rint(operaciones[0]*100)/100);
    }//GEN-LAST:event_btncuadradoActionPerformed

    private void btnrectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrectanguloActionPerformed
        // TODO add your handling code here:
        double base;
        double altura;
                
                base = Double.parseDouble(txtbase.getText());

                altura = Double.parseDouble(txtaltura.getText());
                
                Rectangulo miRectangulo = new Rectangulo(base,altura); 
                liskov(miRectangulo);
                
                txtperimetroR.setText("El perimetro es: "+Math.rint(operaciones[1]*100)/100);
                txtareaR.setText("El area es: "+Math.rint(operaciones[0]*100)/100);
                
        
        
    }//GEN-LAST:event_btnrectanguloActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncirculo;
    private javax.swing.JButton btncuadrado;
    private javax.swing.JButton btnrectangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JLabel txtareaC;
    private javax.swing.JLabel txtareaCu;
    private javax.swing.JLabel txtareaR;
    private javax.swing.JTextField txtbase;
    private javax.swing.JTextField txtlado;
    private javax.swing.JLabel txtperimetroC;
    private javax.swing.JLabel txtperimetroCu;
    private javax.swing.JLabel txtperimetroR;
    private javax.swing.JTextField txtradio;
    // End of variables declaration//GEN-END:variables
}
